name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: add permission
        run: chmod +x ./gradlew
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: cicdsample
          path: build/libs/*.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: cicdsample
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.ORACLE_CLOUD }}
      - name: SCP transfer
        run: scp *.jar ${{ secrets.USER }}@${{ secrets.HOST }}:~/cicd
      - name: Execute remote commands
        run: |
          ssh ${{ secrets.USER }}@${{ secrets.HOST }} "sudo fuser -k 8080/tcp"
          ssh ${{ secrets.USER }}@${{ secrets.HOST }} "sudo nohup java -jar ~/cicd/*.jar &"